package br.com.coursera.test;

// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;


public class SeleniumTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  
  @After
  public void tearDown() {
    driver.quit();
  }
  
  @Test
  public void palavraInexistente() {
    driver.get("http://localhost:8080/MeuWebTradutorMVC/");
    driver.manage().window().setSize(new Dimension(996, 701));
    driver.findElement(By.id("palavra")).click();
    driver.findElement(By.id("palavra")).sendKeys("paralelepipedo");
    driver.findElement(By.cssSelector("input:nth-child(4)")).click();
    driver.findElement(By.cssSelector("h2")).click();
    driver.findElement(By.cssSelector("h2")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("h2"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    assertThat(driver.findElement(By.cssSelector("h2")).getText(), is("paralelepipedo"));
  }
  
  @Test
  public void primeiraPalavraExistente() {
    driver.get("http://localhost:8080/MeuWebTradutorMVC/");
    driver.manage().window().setSize(new Dimension(996, 701));
    driver.findElement(By.id("palavra")).click();
    driver.findElement(By.id("palavra")).sendKeys("casa");
    driver.findElement(By.cssSelector("input:nth-child(4)")).click();
    driver.findElement(By.cssSelector("h2")).click();
    driver.findElement(By.cssSelector("h2")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("h2"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    assertThat(driver.findElement(By.cssSelector("h2")).getText(), is("house"));
  }  

  @Test
  public void segundaPalavraExistente() {
    driver.get("http://localhost:8080/MeuWebTradutorMVC/");
    driver.manage().window().setSize(new Dimension(996, 701));
    driver.findElement(By.id("palavra")).click();
    driver.findElement(By.id("palavra")).sendKeys("moon");
    driver.findElement(By.cssSelector("input:nth-child(4)")).click();
    driver.findElement(By.cssSelector("h2")).click();
    driver.findElement(By.cssSelector("h2")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("h2"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    assertThat(driver.findElement(By.cssSelector("h2")).getText(), is("lua"));
  }  
  
}

